### ISSUE TITLE
How to use Control with pegtl::parse_tree

### ISSUE THREAD

**Issue by mike168m** [taocpp/PEGTL#107]
Hi guys,

I'm trying to add control for error reporting in a compiler and I'm having trouble getting it to work.
There are no outputs or exceptions thrown when I run my code. Here is what I have.

```
/ Errors and Error control 
template<class Rule>
struct ParserError: normal<Rule> {
    static const std::string message;

    template< typename Input, typename... States >
    static void success( const Input&, States&&... ) { 
        brekell::util::LogManager{true}.success(message);
    }

    template< typename Input, typename... States >
    static void failure( const Input&, States&&... ) { 
        brekell::util::LogManager{true}.error(message);
    }

    template<class Input, typename ...States>
    static void raise(const Input& in, States&&...) {
        brekell::util::LogManager{true}.info(message);
        throw parse_error(message, in);
    }
}; 

template<> const std::string 
ParserError<ListExpr>::message = "Invalid list expression!";
template<> const std::string 
ParserError<ValueDecl>::message = "Incorrect value declaration!";
template<> const std::string 
ParserError<MatchExpr>::message = "Invalid Match statement! No value produced!";
```
And I use the control class like this
```
parse_tree::parse< Grammar, parse_tree::node, AstSelector, ParserError>(input);
```

Thanks

**Comment by d-frey** [comment]
The control class for the parse tree wasn't calling its base class' methods, which should be mostly fixed now. I've added those calls now, where the derived class from the parse tree always calls the base class' method first before doing its own work.

That still doesn't explain why `raise` isn't called in your case, which is why I'd like to ask you to test the updated code and if you still see problems, please post a minimal but complete example so that I can reproduce the problem.

**Comment by d-frey** [comment]
Oh, one more thing: When forwarding calls to the base class, the parse tree's control class now omits the internal state for building the parse tree itself, so only the states you pass to the `parse_tree::parse` function are forwarded to the control class you provide.

**Comment by d-frey** [comment]
Aaand that just broke Visual C++. \*sigh\*

**Comment by d-frey** [comment]
I fixed Visual C++, can you try now, please?

**Comment by mike168m** [comment]
Thanks I'll try it out soon.

**Comment by mike168m** [comment]
Can you please provide a short example using controls for error reporting. 
I pulled the latest code and it still doesn't produce an output.

**Comment by ColinH** [comment]
In your initial message you say that there are no outputs or exceptions. Are you using the `must<>` rule, or anything else that would convert a local error (a rule that returns `false`) into a global error (an exception)? Otherwise any and all failures to match will simply result in a `false` returned from the top-level `parse()` function.

**Comment by d-frey** [comment]
No output even for success/failure? That's odd.

An example for error reporting is already part of our code: Have a look at `abnf2pegtl.cpp`, it is using the parse tree with error reporting. Note that your grammar must contain `must`-rules (either `must` directly or something like `if_must`, etc.)

**Comment by mike168m** [comment]
Ahhh that makes sense. Only just saw your comment. I'll try it out again with `must` rules
